"""agent table

Revision ID: 1080cdfc7fc7
Revises: 4071be59dfcf
Create Date: 2025-02-08 13:54:26.642778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1080cdfc7fc7'
down_revision: Union[str, None] = '4071be59dfcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policytable')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policytable',
    sa.Column('policy_uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('policy_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('policy_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('policy_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id_proof', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('passbook', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('photo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('pan_card', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('income_proof', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('nominee_address_proof', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('coverage', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('settlement', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('premium_amount', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age_group', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('income_range', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('policy_uid', name='policytable_pkey'),
    sa.UniqueConstraint('policy_id', name='policytable_policy_id_key'),
    sa.UniqueConstraint('policy_name', name='policytable_policy_name_key')
    )
    # ### end Alembic commands ###
