"""updated

Revision ID: b0d8fba606f6
Revises: ca3d9cea83db
Create Date: 2025-02-27 09:59:30.745741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0d8fba606f6'
down_revision: Union[str, None] = 'ca3d9cea83db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policydetails')
    op.drop_table('policytable')
    op.drop_table('agenttable')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenttable',
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_profile', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agent_userid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agent_idproof', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agent_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agent_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('agent_login_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('busy_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('delete_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('block_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('approval_status', postgresql.ENUM('approved', 'processing', 'rejected', name='approvalstatus'), autoincrement=False, nullable=True),
    sa.Column('is_agent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('agent_id', name='agenttable_pkey'),
    sa.UniqueConstraint('agent_name', name='agenttable_agent_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('policytable',
    sa.Column('policy_uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('policy_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('policy_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('policy_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id_proof', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('passbook', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('photo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('pan_card', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('income_proof', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('nominee_address_proof', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('coverage', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('settlement', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('premium_amount', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age_group', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('income_range', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('delete_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('block_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('policy_uid', name='policytable_pkey'),
    sa.UniqueConstraint('policy_id', name='policytable_policy_id_key'),
    sa.UniqueConstraint('policy_name', name='policytable_policy_name_key')
    )
    op.create_table('policydetails',
    sa.Column('policydetails_uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('policy_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('policy_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nominee_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nominee_relationship', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('coverage', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('settlement', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('premium_amount', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('monthly_amount', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('income_range', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id_proof', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('passbook', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('photo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('pan_card', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('income_proof', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('nominee_address_proof', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('policy_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('payment_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('date_of_payment', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('delete_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('block_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agenttable.agent_id'], name='policydetails_agent_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['usertable.user_id'], name='policydetails_user_id_fkey'),
    sa.PrimaryKeyConstraint('policydetails_uid', name='policydetails_pkey')
    )
    # ### end Alembic commands ###
