"""empty message

Revision ID: bd016fa6b6b7
Revises: 0c43900253f1
Create Date: 2025-02-07 11:36:08.067603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bd016fa6b6b7'
down_revision: Union[str, None] = '0c43900253f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertable', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usertable', 'is_admin')
    # ### end Alembic commands ###
